### ISSUE TITLE
There is no way to tell how many detection or identification reviews are pending

### ISSUE THREAD

**Issue by Danlowe95** [Danlowe95/IBEIS-web#15]
this wil require a new, simple query being added on the wildbook side.  the user will want to know how many reviews are waiting for them.

**Comment by naknomum** [comment]
done.  http://springbreak.wildbook.org/ia?getReviewCounts

**Comment by lee0c** [comment]
I've added a progress bar, and will integrate the review counts thing. Only issue is that currently, the buttons on the left gray out when things are loading and the bar doesn't - I'll work on that.

Edit: Progress bar idea was dropped due to not really being what the user needs to know. Just gonna go with a number of reviews pending

**Comment by Danlowe95** [comment]
Ok, @lee0c if you've got it working feel free to close the issue (same goes for all future ones)

**Comment by lee0c** [comment]
I don't have it working all the way - I'm trying to get the actual data to work and I am having a bit of trouble with that. When it's done I will close it though

**Comment by lee0c** [comment]
I've implemented numbers to show this. Currently those numbers will refresh when the workspace is changed or reloaded, or when any of the sidebar buttons are pushed. When they refresh can be changed fairly easily so I'm going to consider this closed.
